# global configs
memory_folder: ./.db
embedding_model: sentence-transformers/all-MiniLM-L6-v2

# env configs
alfworld:
  env_config_path: tasks/env_configs/alfworld_config.yaml 
  max_steps: 30
  few_shots_num: 1

sciworld:
  env_config_path: tasks/env_configs/sciworld_config.yaml
  max_steps: 30
  few_shots_num: 1
